# -*- coding: utf-8 -*-
"""Mycaptain Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePpJq4GwAn9njim0yx2E7IE0fzJFsfsF
"""

print('Hello world')