# -*- coding: utf-8 -*-
"""Task 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrnZgz59479wa7gjJMromQVIVO8ezsZd
"""

# Line 1: This is a comment
# Line 2: This is another comment

# Line 3: This is the actual code that prints "Hello World!"
print("Hello World!")