# -*- coding: utf-8 -*-
"""Task 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DR1_HSXyRqlDLADtLrqrzRj5NBaTBaZJ
"""

# Step 1: Define the sets
E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

# Step 2: Perform the set operations
union_set = E.union(N)  # Union of E and N
intersection_set = E.intersection(N)  # Intersection of E and N
difference_set = E.difference(N)  # Difference of E and N
symmetric_difference_set = E.symmetric_difference(N)  # Symmetric difference of E and N

# Step 3: Print the results
print(f"Union of E and N is {union_set}")
print(f"Intersection of E and N is {intersection_set}")
print(f"Difference of E and N is {difference_set}")
print(f"Symmetric difference of E and N is {symmetric_difference_set}")