# -*- coding: utf-8 -*-
"""Task 3(2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmgYZyXD6vLEltQQicM0ZUcdGM5ITmJa
"""

# Define the function to get positive numbers from a list
def get_positive_numbers(input_list):
    return [num for num in input_list if num > 0]

# Test the function with given input lists
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Print the output
print("Output for list1:", get_positive_numbers(list1))
print("Output for list2:", get_positive_numbers(list2))