# -*- coding: utf-8 -*-
"""Task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBq3f3JGByHf-0v0i-27O7XOuqI0dkOi
"""

def fibonacci(n):
    sequence = [0, 1]
    while len(sequence) < n:
        next_value = sequence[-1] + sequence[-2]
        sequence.append(next_value)
    return sequence

n_terms = 100
fib_sequence = fibonacci(n_terms)
print(f"Fibonacci sequence with {n_terms} terms: {fib_sequence}")